<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
  <title><?php echo A('owner') ?>'s Music Collection</title>
  <link href="<?php echo Atomik::appAsset(A('style')) ?>"
    rel="stylesheet" type="text/css" />
  <link rel="icon" type="image/vnd.microsoft.icon"
    href="<?php echo Atomik::appAsset('assets/images/favicon.ico') ?>" />
    <meta http-equiv="Content-Type"
      content="application/xhtml+xml; charset=utf-8" />
    <meta name="author" content="" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
  </head>
  <body>
    <div id="content">
      <?php echo $contentForLayout; ?>
    </div>
  </body>
</html>
