<h1>Add a record</h1>

<p>
<form action="<?php echo Atomik::url('@add'); ?>" method="post">

  <table>
    <tr>
      <td class="right">Title</td>
      <td class="left"><input name="title" type="text" size="40" /></td>
    </tr>

    <tr>
      <td class="right">Artist</td>
      <td class="left">
        <select name="artist">
          <?php foreach ($artists as $a): ?>
          <option><?php echo $a ?></option>
          <?php endforeach; ?>
        </select>
      </td>
    </tr>

    <tr>
      <td class="right"></td>
      <td class="left"><input name="new_artist" type="text" size="40" /></td>
    </tr>

    <tr>
      <td class="right">Year (first release)</td>
      <td class="left"><input name="first_year" type="text" size="40" /></td>
    </tr>

    <tr>
      <td class="right">Year (this release)</td>
      <td class="left"><input name="this_year" type="text" size="40" /></td>
    </tr>

    <tr>
      <td class="right">Type</td>
      <td class="left">
        <select name="type">
          <?php foreach ($types as $t): ?>
          <option><?php echo $t ?></option>
          <?php endforeach; ?>
        </select>
      </td>
    </tr>

    <tr>
      <td class="right">Format</td>
      <td class="left">
        <select name="format">
          <?php foreach ($formats as $f): ?>
          <option><?php echo $f ?></option>
          <?php endforeach; ?>
        </select>
      </td>
    </tr>

    <tr>
      <td class="right">Packaging</td>
      <td class="left">
        <select name="packaging">
          <?php foreach ($packagings as $p): ?>
          <option><?php echo $p ?></option>
          <?php endforeach; ?>
        </select>
      </td>
    </tr>

    <tr>
      <td class="right">
        Annotation<br />
        (optional)
      </td>
      <td class="left">
        <textarea name="annotation" rows="4" cols="38"></textarea>
      </td>
    </tr>

  </table>

  <br />
  <input class="button" name="submit" type="submit" value="Save" />
  <input class="button" name="cancel" type="reset" value="Cancel" />

</form>
</p>
