<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fi" lang="fi">
<head>
<title>MusicGhost</title>
<link rel="stylesheet" type="text/css" href="style.css" />
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
</head>
<body>

<h1>Add a record</h1>

<p>
<form action="" method="">

<center>
<table>
<tr>
<td class="right">Title</td>
<td class="left"><input name="title" type="text" size="40" /></td>
</tr>

<tr>
<td class="right">Artist</td>
<td class="left"><input name="artist" type="text" size="40" /></td>
</tr>

<tr>
<td class="right">Year</td>
<td class="left"><input name="year" type="text" size="40" /></td>
</tr>

<tr>
<td class="right">Type</td>
<td class="left"><select>
<option>Album</option>
<option>Single</option>
<option>etc</option>
</select></td>
</tr>

<tr>
<td class="right">Format</td>
<td class="left"><select>
<option>CD</option>
<option>2CD</option>
<option>DVD</option>
</select></td>
</tr>

<tr>
<td class="right">Case</td>
<td class="left"><select>
<option>something</option>
<option>here</option>
<option>etc</option>
</select></td>
</tr>

<tr>
<td class="right">
Annotation<br />
(optional)
</td>
<td class="left">
<textarea rows="4" cols="38"></textarea>
</td>
</tr>

</table>

<br />
<input class="button" name="submit" type="submit" value="Save" /> 
<input class="button" name="cancel" type="reset" value="Cancel" />

</form>
</p>

</body>
</html>