<h1>Control panel</h1>

<div id="container">

  <div id="navigation">
    <ul>
      <?php foreach ($tabs as $t):
        $url = Atomik::url('@control', array('tab' => $t['id']));
        echo '<li';
        if ($tab == $t['id']) echo ' id="selected"';
        echo "><a href=\"$url\" title=\"\">{$t['name']}</a></li>";
      endforeach; ?>
    </ul>
  </div>

  <div id="controlpanel">
  <?php echo $this->errors() ?>
  <p>
  <form action="<?php echo $action ?>" method="post">
      <p>
        <select name="entry">
          <?php echo $this->options($form_values, $form_selected) ?>
        </select>
        <input class="button" name="submit" type="submit" value="Show" />
      </p>

      <table class="form">
        <tr>
          <td class="right">*Name</td>
          <td class="left"><input name="name" type="text" size="40"
          value="<?php echo $form_name ?>" /></td>
        </tr>
        <?php if ($tab == 'artists'): ?>
          <tr>
            <td class="right">Sort name</td>
            <td class="left"><input name="sortname" type="text" size="40"
            value="<?php echo $form_sortname ?>" /></td>
          </tr>
        <?php endif; ?>
        <tr>
          <td class="right">Homepage</td>
          <td class="left"><input name="homepage" type="text" size="40"
          value="<?php echo $form_homepage ?>" /></td>
        </tr>
        <tr>
          <td class="right">Annotation</td>
          <td class="left">
            <textarea name="annotation" rows="4" cols="38"><?php echo $form_annotation ?></textarea>
          </td>
        </tr>
      </table>
      <br />
      <input class="button" name="submit" type="submit" value="Save" />
      <input class="button" name="submit" type="submit" value="Delete" />
    </form>
    </p>
  </div>

  <p><a href="<?php echo Atomik::url('@front') ?>" title="">Front page &raquo;</a></p>

</div>
