<h1>Control panel</h1>

<div id="container">

    <div id="navigation">
        <ul>
            <li id="selected"><a href="" title="">Tab 1</a></li>
            <li><a href="" title="">Tab 2</a></li>
            <li><a href="" title="">Tab 3</a></li>
            <li><a href="" title="">Tab 4</a></li>
            <li><a href="" title="">Tab 5</a></li>
        </ul>
    </div>
    <div id="controlpanel">
        <p>All the content goes here.</p>
    </div>

</div>
