<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fi" lang="fi">
<head>
<title>MusicGhost</title>
<link rel="stylesheet" type="text/css" href="style.css" />
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
</head>
<body>

<h1>Edit the record</h1>

<p>
<form action="" method="">

<center>
<table>
<tr>
<td class="right">Title</td>
<td class="left"><input name="title" type="text" size="40" value="Sample title" /></td>
</tr>

<tr>
<td class="right">Artist</td>
<td class="left"><input name="artist" type="text" size="40" value="Sample artist" /></td>
</tr>

<tr>
<td class="right">Year</td>
<td class="left"><input name="year" type="text" size="40" value="2011" /></td>
</tr>

<tr>
<td class="right">Type</td>
<td class="left"><select>
<option>Album</option>
<option>Single</option>
<option>etc</option>
</select></td>
</tr>

<tr>
<td class="right">Format</td>
<td class="left"><select>
<option>CD</option>
<option>2CD</option>
<option>DVD</option>
</select></td>
</tr>

<tr>
<td class="right">Case</td>
<td class="left"><select>
<option>something</option>
<option>here</option>
<option>etc</option>
</select></td>
</tr>

<tr>
<td class="right">
Annotation<br />
(optional)
</td>
<td class="left">
<textarea rows="4" cols="38">
"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
</textarea>
</td>
</tr>

<tr>
<td class="right">Lent</td>
<td class="left"><input type="checkbox" name="lent" /></td>
</tr>

<tr>
<td class="right">Borrower</td>
<td class="left"><input name="artist" type="text" size="40" value="" /></td>
</tr>

</table>
</center>

<br />
<input class="button" name="submit" type="submit" value="Save" /> 
<input class="button" name="cancel" type="reset" value="Cancel" />

</form>
</p>

</body>
</html>