<p class="right"><?php if ($logged_in): ?>
  <a href="<?php echo Atomik::url('@logout') ?>" title="">Logout</a>
<?php else: ?>
  <a href="<?php echo Atomik::url('@login') ?>" title="">Login &raquo;</a>
<?php endif; ?></p>

<h1><?php echo $name ?>'s Music Collection</h1>
<p>MusicGhost</p>

<img src="<?php echo $logo ?>"title="" alt="" />

<p>
<form action="<?php echo Atomik::url('@front') ?>" method="post">
  List:
  <select name="list">
    <?php echo $this->options($lists, $old_list) ?>
  </select>
  Filter:
  <input name="filter" type="text" size="15" value="<?php echo $old_filter ?>" />
  <input class="button" name="submit" type="submit" value="Show" />
</form>
</p>

<?php if ($logged_in): ?>
<p>
  <a href="<?php echo Atomik::url('@add') ?>"
  title="">Add a record &raquo;</a> |
  <a href="<?php echo Atomik::url('@control', array('tab' => 'artists')) ?>"
  title="">Control panel &raquo;</a>
</p>
<?php endif; ?>

<table class="recordlist">
  <thead>
    <tr>
      <td class="recordlist"><strong>Artist</strong></td>
      <td class="recordlist"><strong>Record</strong></td>
      <td class="recordlist"><strong>Year</strong></td>
      <td class="recordlist"><strong>Format</strong></td>
    </tr>
  </thead>
  <?php foreach ($records as $r): ?>
  <tr>
    <td class="recordlist"><?php echo $r['artist'] ?></td>
    <td class="recordlist">
      <a href="<?php echo $r['url'] ?>"><?php echo $r['title'] ?></a>
    </td>
    <td class="recordlist"><?php echo $r['year'] ?></td>
    <td class="recordlist"><?php echo $r['format'] ?></td>
  </tr>
  <?php endforeach; ?>
</table>
