<p class="right"><a href="login.html" title="">Login &raquo;</a></p>

<h1>Owner's collection</h1>
<p>MusicGhost</p>

<img src="<?php echo Atomik::appAsset('assets/images/logo.png') ?>"
title="" alt="" />

<p>
<form action="" method="">
  <input name="search" type="text" size="20" />
  <input class="button" name="submit" type="submit" value="Search" />
</form>
<a href="search.html" title="">Advanced search &raquo;</a>
</p>

<p>
<form action="" method="">
  List:
  <select>
    <option>Favourites</option>
    <option>Shopping list</option>
    <option>Wish list</option>
  </select>
</form>
</p>


<p><a href="add.html" title="">Add a record &raquo;</a></p>

<table class="recordlist">
  <thead>
    <tr>
      <td class="recordlist"><strong>Artist</strong></td>
      <td class="recordlist"><strong>Record</strong></td>
      <td class="recordlist"><strong>Year</strong></td>
      <td class="recordlist"><strong>Format</strong></td>
    </tr>
  </thead>
  <?php foreach ($records as $r): ?>
  <tr>
    <td class="recordlist"><?php echo $r['name'] ?></td>
    <td class="recordlist"><?php echo $r['title'] ?></td>
    <td class="recordlist"><?php echo $r['first_year'] ?></td>
    <td class="recordlist"><?php echo $r['format'] ?></td>
  </tr>
  <?php endforeach; ?>
</table>
