<p class="right"><a href="login.html" title="">Login &raquo;</a></p>

<h1>Owner's collection</h1>
<p>MusicGhost</p>

<img src="<?php echo Atomik::appAsset('assets/images/logo.png') ?>" title="" alt="" />

<p>
<form action="" method="">
  <input name="search" type="text" size="20" /> 
  <input class="button" name="submit" type="submit" value="Search" />
</form>
<a href="search.html" title="">Advanced search &raquo;</a>
</p>

<p>
<form action="" method="">
  List: 
  <select>
    <option>Favourites</option>
    <option>Shopping list</option>
    <option>Wish list</option>
  </select>
</form>
</p>


<p><a href="add.html" title="">Add a record &raquo;</a></p>

<table class="recordlist">
  <thead>
    <tr>
      <td class="recordlist"><strong>Artist</strong></td>
      <td class="recordlist"><strong>Record</strong></td>
      <td class="recordlist"><strong>Year</strong></td>
      <td class="recordlist"><strong>Format</strong></td>
    </tr>
  </thead>
  <tr>
    <td class="recordlist">Sample artist 1</td>
    <td class="recordlist">Sample record 1</td>
    <td class="recordlist">1998</td>
    <td class="recordlist">CD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 2</td>
    <td class="recordlist">Sample record 2</td>
    <td class="recordlist">2002</td>
    <td class="recordlist">2CD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 3</td>
    <td class="recordlist">Sample record 3</td>
    <td class="recordlist">2006</td>
    <td class="recordlist">CD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 4</td>
    <td class="recordlist">Sample record 4</td>
    <td class="recordlist">1999</td>
    <td class="recordlist">CD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 5</td>
    <td class="recordlist">Sample record 5</td>
    <td class="recordlist">2011</td>
    <td class="recordlist">DVD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 6</td>
    <td class="recordlist">Sample record 6</td>
    <td class="recordlist">1997</td>
    <td class="recordlist">CD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 7</td>
    <td class="recordlist">Sample record 7</td>
    <td class="recordlist">1995</td>
    <td class="recordlist">2CD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 8</td>
    <td class="recordlist">Sample record 8</td>
    <td class="recordlist">2001</td>
    <td class="recordlist">DVD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 9</td>
    <td class="recordlist">Sample record 9</td>
    <td class="recordlist">1998</td>
    <td class="recordlist">CD</td>
  </tr>
  <tr>
    <td class="recordlist">Sample artist 10</td>
    <td class="recordlist">Sample record 10</td>
    <td class="recordlist">1998</td>
    <td class="recordlist">CD</td>
  </tr>
</table>
