<h1>Record info</h1>

<div id="recordinfo">

<img class="recordimage" src="sampleimage.png" alt="" title="" align="left" />

<h2>Sample record</h2>

<p class="left">
<ul>
<li>Artist name</li>
<li>2011</li>
<li>Album</li>
<li>CD</li>
</ul>
</p>

<p class="left">
"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
</p>

</div>

<p><a href="edit.html" title="">Edit record &raquo;</a> | <a href="" title="">Delete record &raquo;</a></p>
