<h1>Record info</h1>

<div id="recordinfo">

  <img class="recordimage"
    src="<?php echo Atomik::appAsset('assets/images/sampleimage.png') ?>"
    alt="" title="" align="left" />

  <h2><?php echo $record['title'] ?></h2>

  <p class="left">
  <ul>
    <li><?php echo $record['artist'] ?></li>
    <li><?php echo $record['first_year'] ?></li>
    <li><?php echo $record['type'] ?></li>
    <li><?php echo $record['format'] ?></li>
  </ul>
  </p>

  <p class="left">
  <?php echo $record['annotation'] ?>
  </p>

</div>

<?php if ($logged_in): ?>
<p><a href="edit.html" title="">Edit record &raquo;</a> |
<a href="" title="">Delete record &raquo;</a></p>
<?php endif; ?>
